import * as React from 'react'
import {
  Award,
  BadgeCheck,
  BarChart3,
  Battery,
  Box,
  Boxes,
  Briefcase,
  Building2,
  CheckCircle2,
  Clock,
  Cog,
  Compass,
  Cpu,
  Droplet,
  Factory,
  Flame,
  Gauge,
  Gem,
  Globe,
  Handshake,
  Hammer,
  Headphones,
  Heart,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Medal,
  Package,
  PackageCheck,
  Phone,
  Recycle,
  Rocket,
  Ruler,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  Sparkles,
  Star,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Truck,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * A curated icon set the AI can reference by keyword for feature cards. Using
 * lucide-react means every icon is a clean, consistent stroke SVG that inherits
 * the theme color via `currentColor`. Unknown keywords fall back to a sensible
 * default so the layout never breaks.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  award: Award,
  certified: BadgeCheck,
  badge: BadgeCheck,
  chart: BarChart3,
  analytics: BarChart3,
  battery: Battery,
  box: Box,
  boxes: Boxes,
  inventory: Boxes,
  briefcase: Briefcase,
  building: Building2,
  factory: Factory,
  check: CheckCircle2,
  quality: ShieldCheck,
  clock: Clock,
  cog: Cog,
  gear: Settings,
  settings: Settings,
  compass: Compass,
  cpu: Cpu,
  tech: Cpu,
  droplet: Droplet,
  water: Droplet,
  flame: Flame,
  heat: Flame,
  gauge: Gauge,
  performance: Gauge,
  gem: Gem,
  premium: Gem,
  globe: Globe,
  global: Globe,
  export: Ship,
  shipping: Truck,
  handshake: Handshake,
  partner: Handshake,
  hammer: Hammer,
  support: Headphones,
  service: Headphones,
  heart: Heart,
  layers: Layers,
  material: Layers,
  leaf: Leaf,
  eco: Leaf,
  sustainable: Leaf,
  lightbulb: Lightbulb,
  innovation: Lightbulb,
  lock: Lock,
  secure: Lock,
  mail: Mail,
  email: Mail,
  location: MapPin,
  medal: Medal,
  package: Package,
  delivery: PackageCheck,
  phone: Phone,
  recycle: Recycle,
  rocket: Rocket,
  ruler: Ruler,
  precision: Ruler,
  shield: Shield,
  ship: Ship,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  thermometer: Thermometer,
  timer: Timer,
  speed: Timer,
  trending: TrendingUp,
  growth: TrendingUp,
  truck: Truck,
  logistics: Truck,
  users: Users,
  team: Users,
  wrench: Wrench,
  custom: Wrench,
  zap: Zap,
  energy: Zap,
  power: Zap,
}

/** Keyword list exposed to the AI prompt so it picks valid icon names. */
export const ICON_KEYWORDS: string[] = Array.from(new Set(Object.keys(ICON_MAP)))

export function resolveIcon(name?: string): LucideIcon {
  if (!name) return Sparkles
  const key = name.toLowerCase().trim()
  return ICON_MAP[key] || Sparkles
}

export const SpecIcon: React.FC<{ name?: string; className?: string; strokeWidth?: number }> = ({
  name,
  className,
  strokeWidth = 1.75,
}) => {
  return React.createElement(resolveIcon(name), {
    className,
    strokeWidth,
    'aria-hidden': true,
  })
}
