/**
 * Assembles a human-readable source bundle from a generated SiteSpec so users
 * can view and download "their code". The live site is rendered from JSX
 * sections (creative mode) and structured section data; this flattens both into
 * a single annotated `.tsx`-ish document: the live hero JSX, every JSX section's
 * real source, the 21st.dev component references, and the full spec JSON.
 */
import type { SiteSpec, SpecSection } from './site-spec'

function banner(title: string): string {
  const line = '='.repeat(Math.max(8, title.length + 4))
  return `// ${line}\n// ${title}\n// ${line}`
}

function sectionLabel(s: SpecSection, i: number): string {
  return `Section #${i + 1} · ${s.kind}`
}

export function buildSiteCodeBundle(spec: SiteSpec): string {
  const parts: string[] = []

  parts.push(banner(`${spec.siteName} — generated by AI Site Generator`))
  const headerMeta = [
    `// theme:    ${spec.themeId}`,
    spec.designId ? `// design:   ${spec.designId}` : '',
    spec.templateRef ? `// template: ${spec.templateRef}` : '',
    `// pages:    ${spec.pages.length}`,
  ]
    .filter(Boolean)
    .join('\n')
  parts.push(headerMeta)

  if (spec.heroJsx && spec.heroJsx.trim()) {
    parts.push(banner('Home Hero (live JSX)'))
    parts.push(spec.heroJsx.trim())
  }

  spec.pages.forEach((page, pi) => {
    const pageTitle = pi === 0 ? 'Home page' : `Page: /${page.path} (${page.navLabel})`
    parts.push(banner(pageTitle))
    page.sections.forEach((section, si) => {
      parts.push(`// ${sectionLabel(section, si)}`)
      if (section.kind === 'jsx') {
        parts.push((section.source || section.code).trim())
      } else {
        // Non-JSX sections are data-driven; emit their structured content so the
        // export is complete and nothing the AI produced is lost.
        parts.push(`const section_${pi}_${si} = ${JSON.stringify(section, null, 2)}`)
      }
    })
  })

  if (spec.componentRefs && spec.componentRefs.length) {
    parts.push(banner('21st.dev component references'))
    spec.componentRefs.forEach((ref) => {
      parts.push(
        `// ${ref.section} · ${ref.componentName}${
          typeof ref.similarity === 'number' ? ` (match ${ref.similarity.toFixed(2)})` : ''
        }`,
      )
      parts.push(ref.code.trim())
    })
  }

  parts.push(banner('Full site spec (JSON)'))
  parts.push(`/*\n${JSON.stringify(spec, null, 2)}\n*/`)

  return parts.join('\n\n') + '\n'
}
